//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Language.Home.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Captivate.Comun.LanguageResources.Home.Home.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users are barraged with annonying and irrelevant ads..
        /// </summary>
        public static string AdIndustryBullet_01 {
            get {
                return ResourceManager.GetString("AdIndustryBullet_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data has become commoditized and is bought and sold with little regard for privacy, relevance or effectiveness..
        /// </summary>
        public static string AdIndustryBullet_02 {
            get {
                return ResourceManager.GetString("AdIndustryBullet_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers find it difficult to make money from their traffic. They monetize their subscribers indirectly rather than directly..
        /// </summary>
        public static string AdIndustryBullet_03 {
            get {
                return ResourceManager.GetString("AdIndustryBullet_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most advertisers are forced to rely on banner &amp; display ads rather than tapping into the effectiveness of publisher subscriber bases..
        /// </summary>
        public static string AdIndustryBullet_04 {
            get {
                return ResourceManager.GetString("AdIndustryBullet_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App partners can&apos;t scale without building a marketplace first. Widespread user adoption is extremely difficult to attain..
        /// </summary>
        public static string AdIndustryBullet_05 {
            get {
                return ResourceManager.GetString("AdIndustryBullet_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Digital Ad Industry.
        /// </summary>
        public static string AdIndustryHeading {
            get {
                return ResourceManager.GetString("AdIndustryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles about us.
        /// </summary>
        public static string ArticlesTitle {
            get {
                return ResourceManager.GetString("ArticlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s how Kind Ads is going to make digital advertising KIND again.
        /// </summary>
        public static string FeaturesTitle {
            get {
                return ResourceManager.GetString("FeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisers save money. Publishers keep more of what they earn..
        /// </summary>
        public static string HeroTextEnd_01 {
            get {
                return ResourceManager.GetString("HeroTextEnd_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users aren&apos;t barraged with annoying and irrelevant ads..
        /// </summary>
        public static string HeroTextEnd_02 {
            get {
                return ResourceManager.GetString("HeroTextEnd_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind Ads is an advertising platform that serves user-friendly ads.
        /// </summary>
        public static string HeroTextStart_01 {
            get {
                return ResourceManager.GetString("HeroTextStart_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to through more effective channels like email and push notifications..
        /// </summary>
        public static string HeroTextStart_02 {
            get {
                return ResourceManager.GetString("HeroTextStart_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus on your campaigns, let us take care of your integrations with top publishers..
        /// </summary>
        public static string IntegrationsText {
            get {
                return ResourceManager.GetString("IntegrationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        public static string IntegrationsTitle {
            get {
                return ResourceManager.GetString("IntegrationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind Ads will show you more releveant ads through channels like email marketing and push notifications..
        /// </summary>
        public static string KindAdsBullet_01 {
            get {
                return ResourceManager.GetString("KindAdsBullet_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users will be able to specify exactly how their data will be used, and be incentivized more allow access via a tokenized rewards pool..
        /// </summary>
        public static string KindAdsBullet_02 {
            get {
                return ResourceManager.GetString("KindAdsBullet_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re allowing publishers to easily sell access to their subscribers directly to advertisers..
        /// </summary>
        public static string KindAdsBullet_03 {
            get {
                return ResourceManager.GetString("KindAdsBullet_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisers will be able to find the publishers based on subscriber quality and run campaigns with confidence..
        /// </summary>
        public static string KindAdsBullet_04 {
            get {
                return ResourceManager.GetString("KindAdsBullet_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tokenized rewards pool is allocated daily to publishers, users AND app partners..
        /// </summary>
        public static string KindAdsBullet_05 {
            get {
                return ResourceManager.GetString("KindAdsBullet_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind Ads Ecosystem.
        /// </summary>
        public static string KindAdsHeading {
            get {
                return ResourceManager.GetString("KindAdsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new era.
        /// </summary>
        public static string MainTitleBold {
            get {
                return ResourceManager.GetString("MainTitleBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of marketing.
        /// </summary>
        public static string MainTitleEnd {
            get {
                return ResourceManager.GetString("MainTitleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet a.
        /// </summary>
        public static string MainTitleStart {
            get {
                return ResourceManager.GetString("MainTitleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For updates and exclusive offers, enter your email below:.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations with Email and Web Push platforms.
        /// </summary>
        public static string RoadmapStep_01 {
            get {
                return ResourceManager.GetString("RoadmapStep_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development of the Kind Ads Display Network.
        /// </summary>
        public static string RoadmapStep_02 {
            get {
                return ResourceManager.GetString("RoadmapStep_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Kind Ads Score.
        /// </summary>
        public static string RoadmapStep_03 {
            get {
                return ResourceManager.GetString("RoadmapStep_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta launch of Kind Ads Marketplace.
        /// </summary>
        public static string RoadmapStep_04 {
            get {
                return ResourceManager.GetString("RoadmapStep_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development of Kind Wallet.
        /// </summary>
        public static string RoadmapStep_05 {
            get {
                return ResourceManager.GetString("RoadmapStep_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart contract ecosystem for Kind Ads ads.
        /// </summary>
        public static string RoadmapStep_06 {
            get {
                return ResourceManager.GetString("RoadmapStep_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnerships with Premium Publishers.
        /// </summary>
        public static string RoadmapStep_07 {
            get {
                return ResourceManager.GetString("RoadmapStep_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official launch of Kind Ads Marketplace.
        /// </summary>
        public static string RoadmapStep_08 {
            get {
                return ResourceManager.GetString("RoadmapStep_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced integrations with App Partners.
        /// </summary>
        public static string RoadmapStep_09 {
            get {
                return ResourceManager.GetString("RoadmapStep_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Roadmap.
        /// </summary>
        public static string RoadmapTitle {
            get {
                return ResourceManager.GetString("RoadmapTitle", resourceCulture);
            }
        }
    }
}
