//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Language.Home.Team {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindAds.Comun.LanguageResources.Home.Team.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caio is a partner of NPBR International LTDA, an ad agency focused on the Latin America market. He is in charge of operations and making sure companies grow their revenue through digital marketing..
        /// </summary>
        public static string CaioBeleza_Bio {
            get {
                return ResourceManager.GetString("CaioBeleza_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrique is the CTO of Blockliss, a full stack and blockchain consulting company.  He is a full stack developer with over 15 years of experience including Solidity, JS, jQuery JSON, Python, MySQL..
        /// </summary>
        public static string EnriqueChavez_Bio {
            get {
                return ResourceManager.GetString("EnriqueChavez_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eric is the founder of Single Grain, a digital marketing agency that helps companies such as Uber, SalesForce, TurboTax, KitchenAid, Random House, Sony Pictures, and Nordstrom grow..
        /// </summary>
        public static string EricSiu_Bio {
            get {
                return ResourceManager.GetString("EricSiu_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaime is a full stack developer. He is an IT professional and entrepreneur with more than 20 years of experience. He worked at Microsoft for 12 years helping top companies in Latin America create scalable cloud architectures..
        /// </summary>
        public static string JaimeSanchez_Bio {
            get {
                return ResourceManager.GetString("JaimeSanchez_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jason is a highly talented web designer whose work has been featured on sites like Mashable, The Atlantic, Fast Company, Business Insider, PCWorld, Forbes, ReadWriteWeb and many others..
        /// </summary>
        public static string JasonCaldwell_Bio {
            get {
                return ResourceManager.GetString("JasonCaldwell_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jay is the founder of Domain Tools (acquired by Trought Convergence, Inc). Jay is an active startup advisor and investor. He currently spends his time acquiring and growing companies..
        /// </summary>
        public static string JayWesterdal_Bio {
            get {
                return ResourceManager.GetString("JayWesterdal_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeremy received his formal education in accounting and real world education in marketing and management in the retail space. Since 2016 he has been focused on digital marketing with an emphasis on blockchain technologies..
        /// </summary>
        public static string JeremyHood_Bio {
            get {
                return ResourceManager.GetString("JeremyHood_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jonathan is the President of Kajabi, a leading publishing platform where people can create and monetize websites. Kajabi users have sold over $300M of digital products via their platform. Prior to Kajabi, Jonathan was the General Manager of Digital Learning at Success Magazine and he was the CEO of Digital Marketer..
        /// </summary>
        public static string JonathanCronstedt_Bio {
            get {
                return ResourceManager.GetString("JonathanCronstedt_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keith has an extensive background in management, particularly with digital marketing products such as HelloBar.  He has the leadership skills and experience to bring the Kind Ads platform to life..
        /// </summary>
        public static string KeithLindner_Bio {
            get {
                return ResourceManager.GetString("KeithLindner_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ken leads marketing teams for technology startups that have been acquired by Cisco, IGT, and Wired Investors. He has helped scale over a dozen online publishers and a six figure agency..
        /// </summary>
        public static string KenRoberts_Bio {
            get {
                return ResourceManager.GetString("KenRoberts_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leury has over 10 years experience in digital marketing. He has in-depth expertise in developing and implementing various marketing strategies. He eats, sleeps and breathes digital marketing and crypto..
        /// </summary>
        public static string LeuryPichardo_Bio {
            get {
                return ResourceManager.GetString("LeuryPichardo_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Kind Ads Executive Team.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadav is a veteran online marketer and a serial entrepreneur. He is the founder and CEO of InboundJuction, an established digital marketing firm. As a digital influencer and a crypto expert, he also advises Blockchain startups and ICOs on marketing, operations, and business development..
        /// </summary>
        public static string NadavDakner_Bio {
            get {
                return ResourceManager.GetString("NadavDakner_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neil Patel is the founder of Crazy Egg, Hello Bar, and KISSmetrics, and founder of QuickSprout. He helps companies like Amazon, NBC, GM, HP and Viacom grow their revenue..
        /// </summary>
        public static string NeilPatel_Bio {
            get {
                return ResourceManager.GetString("NeilPatel_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quinn comes from a strong IT background and has worked for some of the largest companies in North America. He has worked as a database developer and IT specialist in the education, medical and banking sectors.
        /// </summary>
        public static string QuinnHuffman_Bio {
            get {
                return ResourceManager.GetString("QuinnHuffman_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafael is the co-founder and Director of Operations at NPBR International LTDA. Rafael makes sure that the company has proper operational and administrative controls, and reporting structure..
        /// </summary>
        public static string RafaelMayrink_Bio {
            get {
                return ResourceManager.GetString("RafaelMayrink_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saber is the co-founder of Blockchain World Conferences, the co-founder of Blockchain World Conferences and a partner at Prime Block Capital..
        /// </summary>
        public static string SaberAria_Bio {
            get {
                return ResourceManager.GetString("SaberAria_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saulo is the co-founder of NPBR International LTDA, an agency that helps large corporations with their digital marketing needs. Currently they help their clients spend over $100,000,000 dollars a year on marketing..
        /// </summary>
        public static string SauloMedeiros_Bio {
            get {
                return ResourceManager.GetString("SauloMedeiros_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trevor is the founder and CEO of Polymath, a company bringing securities to the blockchain. He is a serial entrepreneur with two technology startup exits. He was also an original advisor/investor to the Ethereum project..
        /// </summary>
        public static string TrevorKoverko_Bio {
            get {
                return ResourceManager.GetString("TrevorKoverko_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vasil is the found of the ever so popular Growth Marketing Conference that has been in Forbes, Huffington Post and Inc. Vasil spends his time investing in the people behind startups by creating this best-practice-focused event..
        /// </summary>
        public static string VasilAzarov_Bio {
            get {
                return ResourceManager.GetString("VasilAzarov_Bio", resourceCulture);
            }
        }
    }
}
