//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Language.Home.Faq {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindAds.Comun.LanguageResources.Home.Faq.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition to cutting out the middleman, blockchain technology allows Kind Ads to protect its user&apos;s privacy and data. No one person or company will have access to your data or be able to use it for their own self-interest..
        /// </summary>
        public static string Answer_01_End {
            get {
                return ResourceManager.GetString("Answer_01_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of blockchain technology, Kind Ads is able to directly connect advertisers to publishers. By cutting out the middleman, advertisers save money and publishers are able to make more..
        /// </summary>
        public static string Answer_01_Start {
            get {
                return ResourceManager.GetString("Answer_01_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Answer_02_End {
            get {
                return ResourceManager.GetString("Answer_02_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ethereum network is one of the most robust and flexible blockchain platforms. It has the largest development community and the Ethereum foundation is dedicated to continually improving it..
        /// </summary>
        public static string Answer_02_Start {
            get {
                return ResourceManager.GetString("Answer_02_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Answer_03_End {
            get {
                return ResourceManager.GetString("Answer_03_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total supply of Kind tokens is 61,000,000. More tokens outside of the 61,000,000 cannot be released, and the token cannot be mined..
        /// </summary>
        public static string Answer_03_Start {
            get {
                return ResourceManager.GetString("Answer_03_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Kind Ads gains more traction, it will expand into native ads, which both Google and Facebook also offer. But by first going after different channels, it allows Kind Ads to build a strong, defensible position..
        /// </summary>
        public static string Answer_04_End {
            get {
                return ResourceManager.GetString("Answer_04_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind Ads is taking a different approach by first going after channels like push notifications and emails that Google and Facebook are not leveraging. This way advertisers and publishers won&apos;t see it as a competing platform, but instead a platform that they can use in addition to Google and Facebook..
        /// </summary>
        public static string Answer_04_Middle {
            get {
                return ResourceManager.GetString("Answer_04_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional digital ad companies like Google have a larger market cap than the whole crypto market. We would be foolish to say we can beat them overnight, as that isn&apos;t realistic..
        /// </summary>
        public static string Answer_04_Start {
            get {
                return ResourceManager.GetString("Answer_04_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition to the Kind Ads goal of making the Internet more kind by leveraging user-friendly ads, the Kind Ads team has a background in advertising. The founding team and advisors have over 31 years of ad agency experience. This allows them to bring advertisers and publishers to the platform while the competitors will struggle to gain as much traction in this respect..
        /// </summary>
        public static string Answer_05_End {
            get {
                return ResourceManager.GetString("Answer_05_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The big differentiator is that Kind Ads is focusing on ad channels that don&apos;t ruin the user experience. For example, as an Internet user, if you subscribe to a nutrition website&apos;s email newsletter and the owner of that site emails you information about a nutritional product that they have tried, tested, and believe will truly benefit you, then the ad isn&apos;t as bad as seeing banners all over the Internet..
        /// </summary>
        public static string Answer_05_Start {
            get {
                return ResourceManager.GetString("Answer_05_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Answer_06_End {
            get {
                return ResourceManager.GetString("Answer_06_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a user, if you choose to share your data so you can be better targeted, you will receive Kind tokens as you see ads served by Kind Ads throughout the web..
        /// </summary>
        public static string Answer_06_Start {
            get {
                return ResourceManager.GetString("Answer_06_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastly, our team and network have access to over 2 million monthly blog readers in the marketing space (in which 51% spend money on digital ads and 43% have publishing sites)..
        /// </summary>
        public static string Answer_07_End {
            get {
                return ResourceManager.GetString("Answer_07_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As for publishers, Kind Ads will be leveraging platforms like WordPress and Kajabi which will get us access to millions of potential publishers..
        /// </summary>
        public static string Answer_07_Middle {
            get {
                return ResourceManager.GetString("Answer_07_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team has a background in running ad agencies, and we also know the founders of other ad agencies. This gives us access to advertisers..
        /// </summary>
        public static string Answer_07_Start {
            get {
                return ResourceManager.GetString("Answer_07_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why does Kind Ads need to use the blockchain to accomplish its goals?.
        /// </summary>
        public static string Question_01 {
            get {
                return ResourceManager.GetString("Question_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why did Kind Ads choose Ethereum over any other blockchain?.
        /// </summary>
        public static string Question_02 {
            get {
                return ResourceManager.GetString("Question_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the total supply of Kind tokens? Will you ever issue more?.
        /// </summary>
        public static string Question_03 {
            get {
                return ResourceManager.GetString("Question_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How will Kind Ads compete against traditional ad networks like Google and Facebook?.
        /// </summary>
        public static string Question_04 {
            get {
                return ResourceManager.GetString("Question_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What makes Kind Ads different than other ad-based blockchain projects?.
        /// </summary>
        public static string Question_05 {
            get {
                return ResourceManager.GetString("Question_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can people who browse the Internet benefit from Kind Ads?.
        /// </summary>
        public static string Question_06 {
            get {
                return ResourceManager.GetString("Question_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How will Kind Ads attract both publishers and advertisers at the same time?.
        /// </summary>
        public static string Question_07 {
            get {
                return ResourceManager.GetString("Question_07", resourceCulture);
            }
        }
    }
}
