//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindAds.Migration.ToCosmos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertiserProfile
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public string Title { get; set; }
        public string TagLine { get; set; }
        public string WebSiteUrl { get; set; }
        public int IndustryId { get; set; }
        public int MountFounded { get; set; }
        public int YearFounded { get; set; }
        public int PeopleInYourBusiness { get; set; }
        public int CountryBusinessInId { get; set; }
        public int YearOfExperience { get; set; }
        public string AdvertiserNeeds { get; set; }
        public string DocumentInsightsUrl { get; set; }
        public string PhotoUrl { get; set; }
        public string IconUrl { get; set; }
        public string OtherInfo { get; set; }
    }
}
