//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindAds.Migration.ToCosmos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublisherProfile
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CountryBusinessInId { get; set; }
        public int YearOfExperience { get; set; }
        public string IconUrl { get; set; }
    }
}
