//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindAds.Migration.ToCosmos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublisherPreference
    {
        public int Id { get; set; }
        public int IndustryId { get; set; }
        public int PublisherProfileId { get; set; }
    }
}
