-- <Migration ID="6547a964-0bd6-47a7-9052-340d0e26d7b6" />
GO

PRINT N'Altering [dbo].[CAMPAIGNs1]'
GO
ALTER TABLE [dbo].[CAMPAIGNs1] ADD
[IdStatus] [int] NULL CONSTRAINT [Campaigns_IdStatus] DEFAULT ((1)),
[CAT_CAMPAIGN_STATUS_IdStatus] [int] NULL
GO
PRINT N'Creating index [IX_FK_CAT_CAMPAIGN_STATUSCAMPAIGN] on [dbo].[CAMPAIGNs1]'
GO
CREATE NONCLUSTERED INDEX [IX_FK_CAT_CAMPAIGN_STATUSCAMPAIGN] ON [dbo].[CAMPAIGNs1] ([CAT_CAMPAIGN_STATUS_IdStatus])
GO
PRINT N'Creating [dbo].[CAT_CAMPAIGN_STATUS]'
GO
CREATE TABLE [dbo].[CAT_CAMPAIGN_STATUS]
(
[IdStatus] [int] NOT NULL IDENTITY(1, 1),
[Descripcion] [varchar] (255) NULL
)
GO
PRINT N'Creating primary key [PK_CAT_CAMPAIGN_STATUS] on [dbo].[CAT_CAMPAIGN_STATUS]'
GO
ALTER TABLE [dbo].[CAT_CAMPAIGN_STATUS] ADD CONSTRAINT [PK_CAT_CAMPAIGN_STATUS] PRIMARY KEY CLUSTERED  ([IdStatus])
GO
PRINT N'Adding foreign keys to [dbo].[CAMPAIGNs1]'
GO
ALTER TABLE [dbo].[CAMPAIGNs1] ADD CONSTRAINT [FK_CAT_CAMPAIGN_STATUSCAMPAIGN] FOREIGN KEY ([CAT_CAMPAIGN_STATUS_IdStatus]) REFERENCES [dbo].[CAT_CAMPAIGN_STATUS] ([IdStatus])
GO
