-- <Migration ID="d4e60545-48ee-448a-941d-33425a971f73" />
GO

PRINT N'Creating [dbo].[PARTNER_SETTINGS]'
GO
CREATE TABLE [dbo].[PARTNER_SETTINGS]
(
[IdPartnerSetting] [uniqueidentifier] NOT NULL,
[SettingName] [nvarchar] (max) NOT NULL,
[SettingValue] [nvarchar] (max) NOT NULL,
[PARTNER_IdPartner] [uniqueidentifier] NOT NULL
)
GO
PRINT N'Creating primary key [PK_PARTNER_SETTINGS] on [dbo].[PARTNER_SETTINGS]'
GO
ALTER TABLE [dbo].[PARTNER_SETTINGS] ADD CONSTRAINT [PK_PARTNER_SETTINGS] PRIMARY KEY CLUSTERED  ([IdPartnerSetting])
GO
PRINT N'Creating index [IX_FK_PARTNERPARTNER_SETTINGS] on [dbo].[PARTNER_SETTINGS]'
GO
CREATE NONCLUSTERED INDEX [IX_FK_PARTNERPARTNER_SETTINGS] ON [dbo].[PARTNER_SETTINGS] ([PARTNER_IdPartner])
GO
PRINT N'Creating [dbo].[PRODUCT_SETTINGS]'
GO
CREATE TABLE [dbo].[PRODUCT_SETTINGS]
(
[IdProductSetting] [uniqueidentifier] NOT NULL,
[SettingName] [nvarchar] (max) NOT NULL,
[SettingValue] [nvarchar] (max) NOT NULL,
[PRODUCT_IdProduct] [uniqueidentifier] NOT NULL
)
GO
PRINT N'Creating primary key [PK_PRODUCT_SETTINGS] on [dbo].[PRODUCT_SETTINGS]'
GO
ALTER TABLE [dbo].[PRODUCT_SETTINGS] ADD CONSTRAINT [PK_PRODUCT_SETTINGS] PRIMARY KEY CLUSTERED  ([IdProductSetting])
GO
PRINT N'Creating index [IX_FK_PRODUCTPRODUCT_SETTINGS] on [dbo].[PRODUCT_SETTINGS]'
GO
CREATE NONCLUSTERED INDEX [IX_FK_PRODUCTPRODUCT_SETTINGS] ON [dbo].[PRODUCT_SETTINGS] ([PRODUCT_IdProduct])
GO
PRINT N'Adding foreign keys to [dbo].[PARTNER_SETTINGS]'
GO
ALTER TABLE [dbo].[PARTNER_SETTINGS] ADD CONSTRAINT [FK_PARTNERPARTNER_SETTINGS] FOREIGN KEY ([PARTNER_IdPartner]) REFERENCES [dbo].[PARTNERS] ([IdPartner])
GO
PRINT N'Adding foreign keys to [dbo].[PRODUCT_SETTINGS]'
GO
ALTER TABLE [dbo].[PRODUCT_SETTINGS] ADD CONSTRAINT [FK_PRODUCTPRODUCT_SETTINGS] FOREIGN KEY ([PRODUCT_IdProduct]) REFERENCES [dbo].[PRODUCTS] ([IdProduct])
GO
