//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindAds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMPAIGN()
        {
            this.TRANSACTIONS_CAPT = new HashSet<TRANSACTIONS_CAPT>();
            this.CAMPAIGN_SETTINGS = new HashSet<CAMPAIGN_SETTINGS>();
            this.CAMPAIGN_CHAT = new HashSet<CAMPAIGN_CHAT>();
        }
    
        public System.Guid IdCampaign { get; set; }
        public string Name { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string AdText { get; set; }
        public string AdURL { get; set; }
        public string AdImage { get; set; }
        public string UTM_Source { get; set; }
        public string UTM_Medium { get; set; }
        public string UTM_Campaign { get; set; }
        public Nullable<int> CAT_CAMPAIGN_STATUS_IdStatus { get; set; }
        public string IdCampaign3rdParty { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTIONS_CAPT> TRANSACTIONS_CAPT { get; set; }
        public virtual CAT_CAMPAIGN_STATUS CAT_CAMPAIGN_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPAIGN_SETTINGS> CAMPAIGN_SETTINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPAIGN_CHAT> CAMPAIGN_CHAT { get; set; }
    }
}
