//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindAds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGN_CHAT
    {
        public System.Guid IdCampaignMessage { get; set; }
        public System.Guid CAMPAIGN_IdCampaign { get; set; }
        public string AspNetUser_IdCreator { get; set; }
        public string CampaignChatMessage { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<int> CampaignChatStatus { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CAMPAIGN CAMPAIGNs1 { get; set; }
    }
}
