//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindAds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTNER_SETTINGS
    {
        public System.Guid IdPartnerSetting { get; set; }
        public string SettingName { get; set; }
        public string SettingValue { get; set; }
        public System.Guid PARTNER_IdPartner { get; set; }
    
        public virtual PARTNER PARTNER { get; set; }
    }
}
