//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace captivate_express_webapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KindadsEntities : DbContext
    {
        public KindadsEntities()
            : base("name=KindadsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CATEGORY> CATEGORIES { get; set; }
        public virtual DbSet<PARTNER_PRODUCT_SETTINGS> PARTNER_PRODUCT_SETTINGS { get; set; }
        public virtual DbSet<PARTNER> PARTNERS { get; set; }
        public virtual DbSet<PRODUCT_TYPE> PRODUCT_TYPE { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<SITE> SITES { get; set; }
        public virtual DbSet<TAG> TAGS { get; set; }
        public virtual DbSet<TRANSACTION_TYPE> TRANSACTION_TYPE { get; set; }
        public virtual DbSet<TRANSACTIONS_CAPT> TRANSACTIONS_CAPT { get; set; }
        public virtual DbSet<CAMPAIGN> CAMPAIGNs1 { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<TRANSACTIONS_EXTERNAL> TRANSACTIONS_EXTERNAL { get; set; }
        public virtual DbSet<CAT_CAMPAIGN_STATUS> CAT_CAMPAIGN_STATUS { get; set; }
        public virtual DbSet<PARTNER_SETTINGS> PARTNER_SETTINGS { get; set; }
        public virtual DbSet<PRODUCT_SETTINGS> PRODUCT_SETTINGS { get; set; }
        public virtual DbSet<CAMPAIGN_SETTINGS> CAMPAIGN_SETTINGS { get; set; }
        public virtual DbSet<CAMPAIGN_CHAT> CAMPAIGN_CHAT { get; set; }
    }
}
